<?php

// Include the config file to establish the database connection
include 'config.php';
session_start(); // Start the session

// Set response header to return JSON
header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Retrieve user input
    $protein_family = $_POST['protein-family'] ?? '';
    $taxonomy = $_POST['taxonomy'] ?? '';

    // Ensure both inputs are provided
    if (empty($protein_family) || empty($taxonomy)) {
        echo json_encode(["status" => "error", "message" => "Protein family and taxonomy are required"]);
        exit;
    }

    // Generate a unique search ID for this query
    $search_id = uniqid('search_', true);

    // Call backend scripts to fetch data and perform analysis
    $command = escapeshellcmd("bash fetch_protein_data.sh '$protein_family' '$taxonomy' '$search_id'");
    $output = shell_exec($command);

    // Ensure protein data is fetched
    if (empty($output)) {
        echo json_encode(["status" => "error", "message" => "No protein data fetched"]);
        exit;
    }

    // Split the output string into an array of protein IDs
    $protein_ids_array = explode("\n", trim($output));

    try {
        // Start a database transaction
        $pdo->beginTransaction();

        // If the user is logged in, store search history
        if (isset($_SESSION['username'])) {
            $username = $_SESSION['username'];
            $stmt = $pdo->prepare("INSERT INTO search_history (search_id, username, Protein_Family, Taxonomy) VALUES (?, ?, ?, ?)");
            $stmt->execute([$search_id, $username, $protein_family, $taxonomy]);
        }

        // Read the FASTA file generated by the shell script
        $fasta_file = "protein_results/{$search_id}.fasta";

        if (!file_exists($fasta_file)) {
            throw new Exception("No protein data fetched");
        }

        $fasta_contents = file_get_contents($fasta_file);

        // Use regex to extract individual FASTA sequences
        preg_match_all("/>(\S+)\s*(.*?)\n([^>]*)/s", $fasta_contents, $matches, PREG_SET_ORDER);

        // Create a dictionary mapping accession numbers to their corresponding FASTA sequences
        $fasta_dict = [];
        foreach ($matches as $match) {
            $acc_number = trim($match[1]); // Extract the accession number
            $header = trim($match[2]); // Extract the header (optional)
            
            // Remove newlines and whitespace from the sequence to ensure a continuous string
            $sequence = preg_replace('/\s+/', '', trim($match[3]));

            // Extract protein name and species from header (assumes a specific format)
            preg_match("/\[(.*?)\]/", $header, $species_match);
            $species = $species_match[1] ?? ''; // Species extracted from the header
            $protein_name = preg_replace("/\s*\[.*\]/", '', $header); // Remove species information from the protein name

            // Store the FASTA sequence and related information
            $fasta_dict[$acc_number] = [
                'sequence' => $sequence,
                'protein_name' => $protein_name,
                'species' => $species
            ];
        }

        // Prepare the SQL statement for inserting protein sequences into the database
        $sql = "INSERT INTO protein_sequences (search_id, protein_id, protein_name, species, sequence) VALUES (?, ?, ?, ?, ?)";
        $stmt = $pdo->prepare($sql);

        // Iterate through the protein IDs obtained from the shell script output
        foreach ($protein_ids_array as $protein_id) {
            if (isset($fasta_dict[$protein_id])) {
                // If a corresponding FASTA sequence exists, insert it into the database
                $stmt->execute([
                    $search_id,
                    $protein_id,
                    $fasta_dict[$protein_id]['protein_name'],
                    $fasta_dict[$protein_id]['species'],
                    $fasta_dict[$protein_id]['sequence']
                ]);
            } else {
                // If no matching sequence is found, throw an exception
                throw new Exception("No FASTA sequence found for protein ID: $protein_id");
            }
        }

        // Commit transaction
        $pdo->commit();

        // Return success response
        echo json_encode(["status" => "success", "search_id" => $search_id]);

    } catch (Exception $e) {
        // Rollback on error
        $pdo->rollBack();
        echo json_encode(["status" => "error", "message" => $e->getMessage()]);
    }
}
?>
